### ISSUE TITLE
0.36 fails to build

### ISSUE THREAD

**Issue by aheart** [blackbeam/mysql_async#347]
I have a small project that works well on 0.35.1, but on 0.36 it fails to build and the errors are in the source code of mysql_async.
You don't even need any code to reproduce this, just adding the crate to an empty project is sufficient to see these errors.

```
error[E0599]: no associated item named `Conn` found for struct `connection_like::Connection<'_, '_>` in the current scope
   --> /home/alex/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/mysql_async-0.36.0/src/conn/binlog_stream/mod.rs:100:25
    |
100 |             Connection::Conn(conn) => {
    |                         ^^^^ associated item not found in `Connection<'_, '_>`
    |
   ::: /home/alex/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/mysql_async-0.36.0/src/connection_like/mod.rs:50:1
    |
50  | pub struct Connection<'a, 't: 'a> {
    | --------------------------------- associated item `Conn` not found for this struct

error[E0599]: no associated item named `ConnMut` found for struct `connection_like::Connection<'_, '_>` in the current scope
   --> /home/alex/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/mysql_async-0.36.0/src/conn/binlog_stream/mod.rs:109:25
    |
109 |             Connection::ConnMut(_) => {}
    |                         ^^^^^^^ associated item not found in `Connection<'_, '_>`
    |
   ::: /home/alex/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/mysql_async-0.36.0/src/connection_like/mod.rs:50:1
    |
50  | pub struct Connection<'a, 't: 'a> {
    | --------------------------------- associated item `ConnMut` not found for this struct

error[E0599]: no associated item named `Tx` found for struct `connection_like::Connection<'_, '_>` in the current scope
   --> /home/alex/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/mysql_async-0.36.0/src/conn/binlog_stream/mod.rs:110:25
    |
110 |             Connection::Tx(_) => {}
    |                         ^^ associated item not found in `Connection<'_, '_>`
    |
   ::: /home/alex/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/mysql_async-0.36.0/src/connection_like/mod.rs:50:1
    |
50  | pub struct Connection<'a, 't: 'a> {
    | --------------------------------- associated item `Tx` not found for this struct

For more information about this error, try `rustc --explain E0599`.
```

**Comment by blackbeam** [comment]
Fixed in [v0.36.1](https://github.com/blackbeam/mysql_async/releases/tag/v0.36.1)
