### ISSUE TITLE
getting compilation error in 17.1

### ISSUE THREAD

**Issue by surajpayu** [blackbeam/mysql_async#37]
error[E0432]: unresolved import `tokio::net::tcp`
  --> /home/suraj.prakash/.cargo/registry/src/github.com-1ecc6299db9ec823/mysql_async-0.17.1/src/io/futures/connecting_stream.rs:16:18
   |
16 | use tokio::net::{tcp::ConnectFuture, TcpStream};
   |                  ^^^ could not find `tcp` in `net`

error: aborting due to previous error

**Comment by blackbeam** [comment]
Hi.

Looks like it won't work with tokio < 0.1.9. I'll add this constraint to the Cargo.toml in the next version.
`cargo update` may help you with this problem if your project does not depend on something that strictly requires tokio <= 0.1.8.

**Comment by blackbeam** [comment]
Fixed in [v0.17.2](https://github.com/blackbeam/mysql_async/releases/tag/v0.17.2).
